"""Gemini-powered violation report generator."""

from __future__ import annotations

import base64
import io
import json
import logging
import re
import threading
import time
from datetime import datetime

from google import genai
from PIL import Image

from src.api.schemas import AlertReportRequest, EventReport, HistoryEvent
from src.config.settings import get_settings
from src.core.history import get_history_event, resolve_history_image_path

logger = logging.getLogger(__name__)
settings = get_settings()

# ── Rate limiter: max 1 Gemini call per 5 s (≤12/min, safely under free-tier 15/min) ──
_rate_lock = threading.Lock()
_last_call_at: float = 0.0
_MIN_INTERVAL = 5.0  # seconds between calls

# ── In-flight dedup: prevent two threads generating the same alert_id simultaneously ──
_inflight: dict[str, threading.Event] = {}
_inflight_lock = threading.Lock()

_RISK_FALLBACK: dict[str, str] = {
    "VI_PHAM": "CAO",
    "NO_HELMET": "CAO",
    "NGHI_NGO": "TRUNG BÌNH",
}

_PROMPT_TEMPLATE = """Bạn là chuyên gia an toàn lao động. Phân tích thông tin vi phạm sau và sinh báo cáo tiếng Việt chuyên nghiệp.

Thông tin:
- Loại vi phạm: {type_vi}
- Thời gian: {timestamp}
- Nguồn camera: {source}
- Số người vi phạm: {num_violators}

Trả về JSON (không thêm markdown, không giải thích):
{{
  "description": "Mô tả chi tiết tình huống (2-3 câu)",
  "risk_level": "CAO",
  "recommendations": ["Khuyến nghị 1", "Khuyến nghị 2", "Khuyến nghị 3"]
}}

risk_level phải là một trong: THẤP, TRUNG BÌNH, CAO, NGHIÊM TRỌNG."""


def _parse_retry_after(exc_str: str) -> float:
    """Extract retryDelay seconds from a 429 error string, default 60s."""
    m = re.search(r"retryDelay.*?['\"](\d+)s", exc_str)
    return float(m.group(1)) + 2 if m else 60.0


def _call_gemini(prompt: str, crop_image: Image.Image | None) -> dict:
    api_key = settings.gemini_api_key
    if not api_key:
        raise ValueError("GEMINI_API_KEY chưa được cấu hình trong .env")

    client = genai.Client(api_key=api_key)
    parts: list = [prompt]
    if crop_image is not None:
        parts.append(crop_image)

    last_exc: Exception = RuntimeError("unknown")
    for attempt in range(3):
        # Enforce minimum interval between calls
        global _last_call_at
        with _rate_lock:
            gap = _MIN_INTERVAL - (time.monotonic() - _last_call_at)
            if gap > 0:
                logger.debug("Rate limiter: waiting %.1fs before Gemini call", gap)
                time.sleep(gap)
            _last_call_at = time.monotonic()

        try:
            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=parts,
            )
            text = response.text.strip()
            if text.startswith("```"):
                lines = text.split("\n")
                text = "\n".join(lines[1:-1] if lines[-1] == "```" else lines[1:])
            return json.loads(text)
        except Exception as exc:
            last_exc = exc
            is_rate_limit = "429" in str(exc) or "RESOURCE_EXHAUSTED" in str(exc)
            if is_rate_limit and attempt < 2:
                wait = _parse_retry_after(str(exc))
                logger.warning("Gemini 429 (attempt %d), retrying in %.0fs…", attempt + 1, wait)
                time.sleep(wait)
            else:
                raise last_exc
    raise last_exc


def _make_fallback_report(event_id: str, class_name: str, error: str) -> EventReport:
    risk = _RISK_FALLBACK.get(class_name.upper(), "TRUNG BÌNH")
    return EventReport(
        event_id=event_id,
        description=f"Không thể sinh báo cáo tự động ({error}). Vi phạm liên quan đến: {class_name}.",
        risk_level=risk,
        recommendations=[
            "Nhắc nhở người lao động đội mũ bảo hộ đúng quy định.",
            "Kiểm tra lại quy trình giám sát an toàn tại khu vực này.",
            "Ghi nhận sự kiện để theo dõi tần suất vi phạm.",
        ],
        generated_at=datetime.now().isoformat(),
        status="failed",
    )


def _with_inflight_dedup(alert_id: str, generate_fn) -> EventReport:
    """
    If alert_id is already being generated by another thread, wait for it to
    finish and read from cache instead of launching a second Gemini call.
    """
    with _inflight_lock:
        if alert_id in _inflight:
            event = _inflight[alert_id]
            already_running = True
        else:
            event = threading.Event()
            _inflight[alert_id] = event
            already_running = False

    if already_running:
        logger.debug("Waiting for in-flight report %s…", alert_id)
        event.wait(timeout=120)
        cache_path = settings.reports_dir / f"{alert_id}.json"
        if cache_path.exists():
            try:
                return EventReport(**json.loads(cache_path.read_text(encoding="utf-8")))
            except Exception:
                pass
        return _make_fallback_report(alert_id, "unknown", "in-flight wait timed out")

    try:
        return generate_fn()
    finally:
        with _inflight_lock:
            _inflight.pop(alert_id, None)
        event.set()


def generate_from_alert(request: AlertReportRequest, alert_id: str) -> EventReport:
    """Generate a report from raw alert data (base64 crop + metadata)."""
    cache_path = settings.reports_dir / f"{alert_id}.json"
    if cache_path.exists():
        try:
            return EventReport(**json.loads(cache_path.read_text(encoding="utf-8")))
        except Exception:
            pass

    def _generate() -> EventReport:
        type_map = {"NO_HELMET": "không đội mũ bảo hộ", "NGHI_NGO": "nghi ngờ vi phạm"}
        type_vi = type_map.get(request.class_name.upper(), request.class_name)
        prompt = _PROMPT_TEMPLATE.format(
            type_vi=type_vi,
            timestamp=request.timestamp,
            source=request.source,
            num_violators=request.num_violators,
        )

        crop_image: Image.Image | None = None
        if request.crop_base64:
            try:
                img_bytes = base64.b64decode(request.crop_base64)
                crop_image = Image.open(io.BytesIO(img_bytes)).convert("RGB")
            except Exception:
                logger.warning("Could not decode crop_base64 for alert %s", alert_id)

        try:
            data = _call_gemini(prompt, crop_image)
            report = EventReport(
                event_id=alert_id,
                description=data["description"],
                risk_level=data["risk_level"],
                recommendations=data["recommendations"],
                generated_at=datetime.now().isoformat(),
                status="ready",
            )
        except Exception as exc:
            logger.warning("Gemini failed for alert %s: %s", alert_id, exc)
            report = _make_fallback_report(alert_id, request.class_name, str(exc)[:80])

        cache_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
        return report

    return _with_inflight_dedup(alert_id, _generate)


def get_or_generate_report_for_event(event_id: str) -> EventReport | None:
    """Get cached report or generate one from a HistoryEvent."""
    cache_path = settings.reports_dir / f"{event_id}.json"
    if cache_path.exists():
        try:
            return EventReport(**json.loads(cache_path.read_text(encoding="utf-8")))
        except Exception:
            pass

    event = get_history_event(event_id)
    if event is None:
        return None

    def _generate() -> EventReport:
        type_map = {"VI_PHAM": "vi phạm không đội mũ bảo hộ", "NGHI_NGO": "nghi ngờ vi phạm"}
        type_vi = type_map.get(event.type, event.type)
        prompt = _PROMPT_TEMPLATE.format(
            type_vi=type_vi,
            timestamp=event.timestamp,
            source=event.source,
            num_violators=event.num_violators,
        )

        crop_image: Image.Image | None = None
        if event.crop_image_urls:
            try:
                img_path = resolve_history_image_path(event.crop_image_urls[0])
                crop_image = Image.open(img_path).convert("RGB")
            except Exception:
                pass

        try:
            data = _call_gemini(prompt, crop_image)
            report = EventReport(
                event_id=event_id,
                description=data["description"],
                risk_level=data["risk_level"],
                recommendations=data["recommendations"],
                generated_at=datetime.now().isoformat(),
                status="ready",
            )
        except Exception as exc:
            logger.warning("Gemini failed for event %s: %s", event_id, exc)
            report = _make_fallback_report(event_id, event.type, str(exc)[:80])

        cache_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
        return report

    return _with_inflight_dedup(event_id, _generate)


def bulk_generate_reports(events: list[HistoryEvent]) -> list[EventReport]:
    """Generate (or load cached) reports for a list of HistoryEvents."""
    reports = []
    for event in events:
        report = get_or_generate_report_for_event(event.id)
        if report is not None:
            reports.append(report)
    return reports
